site_name: Arctic
site_description: Arctic is a pluggable streaming lakehouse service layer on top of hive and iceberg

docs_dir: '../../docs/ch'
site_dir: '../../generated/ch'
remote_name: arctic-site
use_directory_urls: true
repo_url: https://github.com/NetEase/arctic
repo_name: NetEase/arctic
edit_uri: ""

# pip install mkdocs-material
theme:
  font:
    text: Msyh
  name: material
  language: zh
  favicon: images/favicon.ico
  logo: images/arctic_banner.png
  palette:
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/github

extra:
  search:
    language: 'en'
  alternate:
    - name: 中文
      link: /ch/
      lang: zh
    - name: English
      link: /en/
      lang: en

copyright: "Copyright 2018-2021"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Overview: index.md
  - Concepts:
    - Catalogs: concepts/catalogs.md
    - Table formats: concepts/table-formats.md
    - Self-optimizing: concepts/self-optimizing.md
    - Table watermark: concepts/table-watermark.md
  - Quick Start:
      - Setup: empty.md
      - Quick demo: empty.md
      - CDC ingestion: empty.md
  - Admin guide:
    - Deployment: empty.md
    - Managing catalogs: empty.md
    - Managing tables: empty.md
    - Managing optimizers: empty.md
    - Using kyuubi through terminal: empty.md
    - Metrics: empty.md
  - Configurations: configurations.md
  - Flink integration:
    - Getting Started: flink/flink-get-started.md
    - Flink DDL: flink/flink-ddl.md
    - Flink DML: flink/flink-dml.md
    - Flink DIM: flink/flink-dim.md
    - Flink DataStream: flink/flink-ds.md
    - Using Kafka as Logstore: flink/hidden-kafka.md
    - Flink CDC to Arctic: flink/flink-cdc-to-arctic.md
  - Spark integration:
    - Getting Started: spark/spark-get-started.md
    - Spark DDL: spark/spark-ddl.md
    - Spark DML: spark/spark-dml.md
    - Spark DataFrame: spark/spark-dataframe.md
  - MPP integration:
    - Trino: mpp/trino.md
    - Impala: empty.md
  - Benchmark: benchmark.md
  - Roadmap: roadmap.md
  - Contributing: contribute.md


plugins:
  - search

extra_css:
  - stylesheets/extra.css